### PR TITLE
patch-1

### PR DESCRIPTION
**Pull request by Artem13327**

### CODE REVIEW

**Comment by realeatham** [comment]
what is this for

**Comment by sosauce** [comment]
i wonder lmao

**Comment by sosauce** [comment]
Oh yeah sorry, i'm on macOS so it creayes these files

**Comment by sosauce** [comment]
I mean, it shouldn't be an issue if they do, .DS_STORE only serve to keep some data about folders for macOS

**Comment by sosauce** [comment]
Shouldn't affect build and the project at all if you are on Windows

**Pull request merged**
