### PR TITLE
Fixed button order

### PR DESCRIPTION
**Pull request by realeatham**
Issue #33 solved. Found some new issues i will make an issue for later.

### CODE REVIEW

**Comment by realeatham** [comment]
after this goes thru i will make a pull request for the haptic feedback being softer

**Comment by sosauce** [comment]
I already changed some things so pulling would remove all my code

**Comment by realeatham** [comment]
what have you changed

**Comment by sosauce** [comment]
see in [2.5.2](https://github.com/sosauce/CuteCalc/releases/tag/v2.5.2)

**Comment by sosauce** [comment]
Please don't open merge request unless you add big changes, I'm on the spot for bug fix and UI  improvment, it also breaks my SDK location wich is annoying to re-configure

**Comment by realeatham** [comment]
Ok I won't. But just so you know, to avoid breaking the sdk location you should not have a file on GitHub called local.properties and not upload one to GitHub. To make sure this doesn't happen, delete local.properties, then copy local.properties from another project. When it asks you if to add to git or not, say no.

**Pull request closed without merging**
