### PR TITLE
Added English Translation File (Same as default)

### PR DESCRIPTION
**Pull request by realeatham**
Added English Translation File (Same as default)

### CODE REVIEW

**Comment by sosauce** [comment]
What's the point of translating a calculator app tho ?

**Comment by realeatham** [comment]
> What's the point of translating a calculator app tho ?

There is none, and i only know English anyway.

**Comment by sosauce** [comment]
Okay, but can you be carefull before doing merge request ? Some things were broken I had to fix them 😄

**Comment by realeatham** [comment]
Ok

**Pull request merged**
